version: "3.7"

services:
  db:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interestedy
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
